/*
 * Created on 2017-11-09 ( Date ISO 2017-11-09 - Time 10:27:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean EmployeeRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class EmployeeRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class EmployeeRecord getters and setters ..." );
		
		EmployeeRecord employeeRecord = new EmployeeRecord();


		//--- Test setter/getter for attribute "code"  ( model type : String / wrapperType : String )
		employeeRecord.setCode( "AAAA" ) ;
		Assert.assertEquals( "AAAA", employeeRecord.getCode() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "shopCode"  ( model type : String / wrapperType : String )
		employeeRecord.setShopCode( "AAA" ) ;
		Assert.assertEquals( "AAA", employeeRecord.getShopCode() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "firstName"  ( model type : String / wrapperType : String )
		employeeRecord.setFirstName( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", employeeRecord.getFirstName() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "lastName"  ( model type : String / wrapperType : String )
		employeeRecord.setLastName( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", employeeRecord.getLastName() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "manager"  ( model type : Boolean / wrapperType : Boolean )
		employeeRecord.setManager( Boolean.valueOf(true) ) ;
		Assert.assertEquals( Boolean.valueOf(true), employeeRecord.getManager() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "badgeNumber"  ( model type : Integer / wrapperType : Integer )
		employeeRecord.setBadgeNumber( Integer.valueOf(100) ) ;
		Assert.assertEquals( Integer.valueOf(100), employeeRecord.getBadgeNumber() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "email"  ( model type : String / wrapperType : String )
		employeeRecord.setEmail( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", employeeRecord.getEmail() ) ; // Not primitive type in model


	}

}
