/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:02:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean EmployeeGroupRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class EmployeeGroupRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class EmployeeGroupRecord getters and setters ..." );
		
		EmployeeGroupRecord employeeGroupRecord = new EmployeeGroupRecord();


		//--- Test setter/getter for attribute "employeeCode"  ( model type : String / wrapperType : String )
		employeeGroupRecord.setEmployeeCode( "AAAA" ) ;
		Assert.assertEquals( "AAAA", employeeGroupRecord.getEmployeeCode() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "groupId"  ( model type : Short / wrapperType : Short )
		employeeGroupRecord.setGroupId( Short.valueOf((short)1) ) ;
		Assert.assertEquals( Short.valueOf((short)1), employeeGroupRecord.getGroupId() ) ; // Not primitive type in model


	}

}
