/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:03:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.web.rest.commons;

import java.util.logging.Logger;

/**
 * Abstract REST resource controller providing a logger <br>
 *  
 * @author Telosys
 *
 */
public abstract class AbstractResourceController {

	protected final Logger logger ;
	
	/**
	 * Constructor
	 */
	public AbstractResourceController() {
		super();
		this.logger = Logger.getLogger(this.getClass().getCanonicalName()); 

		this.logger.setLevel(LoggerLevel.LEVEL);
	}
}
