/*
 * Created on 2017-11-03 ( Time 15:03:35 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.AuthorRecord;
import org.demo.data.record.listitem.AuthorListItem;


//--- Services 
import org.demo.persistence.AuthorPersistence;
// import org.demo.business.service.impl.AuthorServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'Author' management.
 */
@Path("/author")
public class AuthorResource extends AbstractResourceController {

	private AuthorPersistence authorService = PersistenceServiceProvider.getService(AuthorPersistence.class);

	/**
	 * Constructor
	 */
	public AuthorResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all author entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<AuthorRecord> findAll() {
		logger.info("findAll()...");
		return authorService.findAll();
	}

	/**
	 * Retrieves a author using the given id.
	 * @param id id
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{id}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("id") Integer id) {
		logger.info("findById("+id+")...");
		AuthorRecord record = authorService.findById(id);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new author.
	 * @param author author
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(AuthorRecord author) {
		logger.info("create()...");
		if ( authorService.exists(author) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			AuthorRecord record = authorService.create(author);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the author identified by the given id
	 * @param author author entity
	 * @param id id 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{id}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public AuthorRecord update(AuthorRecord author, @PathParam("id") Integer id) {
	public Response update(AuthorRecord author, @PathParam("id") Integer id) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		author.setId( id );
		boolean updated = authorService.update(author);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given author.
	 * @param author author entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(AuthorRecord author) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! authorService.exists(author) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		AuthorRecord record = authorService.save(author);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a author.
	 * @param id id
	 */
	@DELETE
	@Path("{id}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("id") Integer id) {
	public Response delete(@PathParam("id") Integer id) {
		logger.info("delete("+id+")...");
		// authorService.deleteById(id);
		boolean deleted = authorService.deleteById(id);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/authors-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<AuthorListItem> listItems() {
		logger.info("listItems()...");
		List<AuthorRecord> list = authorService.findAll();
		List<AuthorListItem> items = new LinkedList<AuthorListItem>();
		for ( AuthorRecord author : list ) {
			items.add(new AuthorListItem( author ) );
		}
		return items;
	}

}
