/*
 * Created on 2017-11-03 ( Time 15:03:35 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.BadgeRecord;
import org.demo.data.record.listitem.BadgeListItem;


//--- Services 
import org.demo.persistence.BadgePersistence;
// import org.demo.business.service.impl.BadgeServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'Badge' management.
 */
@Path("/badge")
public class BadgeResource extends AbstractResourceController {

	private BadgePersistence badgeService = PersistenceServiceProvider.getService(BadgePersistence.class);

	/**
	 * Constructor
	 */
	public BadgeResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all badge entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<BadgeRecord> findAll() {
		logger.info("findAll()...");
		return badgeService.findAll();
	}

	/**
	 * Retrieves a badge using the given id.
	 * @param badgeNumber badgeNumber
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{badgeNumber}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("badgeNumber") Integer badgeNumber) {
		logger.info("findById("+badgeNumber+")...");
		BadgeRecord record = badgeService.findById(badgeNumber);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new badge.
	 * @param badge badge
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(BadgeRecord badge) {
		logger.info("create()...");
		if ( badgeService.exists(badge) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			BadgeRecord record = badgeService.create(badge);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the badge identified by the given id
	 * @param badge badge entity
	 * @param badgeNumber badgeNumber 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{badgeNumber}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public BadgeRecord update(BadgeRecord badge, @PathParam("badgeNumber") Integer badgeNumber) {
	public Response update(BadgeRecord badge, @PathParam("badgeNumber") Integer badgeNumber) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		badge.setBadgeNumber( badgeNumber );
		boolean updated = badgeService.update(badge);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given badge.
	 * @param badge badge entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(BadgeRecord badge) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! badgeService.exists(badge) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		BadgeRecord record = badgeService.save(badge);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a badge.
	 * @param badgeNumber badgeNumber
	 */
	@DELETE
	@Path("{badgeNumber}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("badgeNumber") Integer badgeNumber) {
	public Response delete(@PathParam("badgeNumber") Integer badgeNumber) {
		logger.info("delete("+badgeNumber+")...");
		// badgeService.deleteById(badgeNumber);
		boolean deleted = badgeService.deleteById(badgeNumber);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/badges-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<BadgeListItem> listItems() {
		logger.info("listItems()...");
		List<BadgeRecord> list = badgeService.findAll();
		List<BadgeListItem> items = new LinkedList<BadgeListItem>();
		for ( BadgeRecord badge : list ) {
			items.add(new BadgeListItem( badge ) );
		}
		return items;
	}

}
