/*
 * Created on 2017-11-03 ( Time 15:03:35 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.CountryRecord;
import org.demo.data.record.listitem.CountryListItem;


//--- Services 
import org.demo.persistence.CountryPersistence;
// import org.demo.business.service.impl.CountryServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'Country' management.
 */
@Path("/country")
public class CountryResource extends AbstractResourceController {

	private CountryPersistence countryService = PersistenceServiceProvider.getService(CountryPersistence.class);

	/**
	 * Constructor
	 */
	public CountryResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all country entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<CountryRecord> findAll() {
		logger.info("findAll()...");
		return countryService.findAll();
	}

	/**
	 * Retrieves a country using the given id.
	 * @param code code
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{code}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("code") String code) {
		logger.info("findById("+code+")...");
		CountryRecord record = countryService.findById(code);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new country.
	 * @param country country
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(CountryRecord country) {
		logger.info("create()...");
		if ( countryService.exists(country) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			CountryRecord record = countryService.create(country);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the country identified by the given id
	 * @param country country entity
	 * @param code code 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{code}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public CountryRecord update(CountryRecord country, @PathParam("code") String code) {
	public Response update(CountryRecord country, @PathParam("code") String code) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		country.setCode( code );
		boolean updated = countryService.update(country);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given country.
	 * @param country country entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(CountryRecord country) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! countryService.exists(country) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		CountryRecord record = countryService.save(country);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a country.
	 * @param code code
	 */
	@DELETE
	@Path("{code}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("code") String code) {
	public Response delete(@PathParam("code") String code) {
		logger.info("delete("+code+")...");
		// countryService.deleteById(code);
		boolean deleted = countryService.deleteById(code);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/countrys-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<CountryListItem> listItems() {
		logger.info("listItems()...");
		List<CountryRecord> list = countryService.findAll();
		List<CountryListItem> items = new LinkedList<CountryListItem>();
		for ( CountryRecord country : list ) {
			items.add(new CountryListItem( country ) );
		}
		return items;
	}

}
