/*
 * Created on 2017-11-09 ( Time 10:27:49 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.EmployeeRecord;
import org.demo.data.record.listitem.EmployeeListItem;


//--- Services 
import org.demo.persistence.EmployeePersistence;
// import org.demo.business.service.impl.EmployeeServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'Employee' management.
 */
@Path("/employee")
public class EmployeeResource extends AbstractResourceController {

	private EmployeePersistence employeeService = PersistenceServiceProvider.getService(EmployeePersistence.class);

	/**
	 * Constructor
	 */
	public EmployeeResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all employee entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<EmployeeRecord> findAll() {
		logger.info("findAll()...");
		return employeeService.findAll();
	}

	/**
	 * Retrieves a employee using the given id.
	 * @param code code
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{code}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("code") String code) {
		logger.info("findById("+code+")...");
		EmployeeRecord record = employeeService.findById(code);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new employee.
	 * @param employee employee
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(EmployeeRecord employee) {
		logger.info("create()...");
		if ( employeeService.exists(employee) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			EmployeeRecord record = employeeService.create(employee);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the employee identified by the given id
	 * @param employee employee entity
	 * @param code code 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{code}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public EmployeeRecord update(EmployeeRecord employee, @PathParam("code") String code) {
	public Response update(EmployeeRecord employee, @PathParam("code") String code) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		employee.setCode( code );
		boolean updated = employeeService.update(employee);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given employee.
	 * @param employee employee entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(EmployeeRecord employee) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! employeeService.exists(employee) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		EmployeeRecord record = employeeService.save(employee);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a employee.
	 * @param code code
	 */
	@DELETE
	@Path("{code}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("code") String code) {
	public Response delete(@PathParam("code") String code) {
		logger.info("delete("+code+")...");
		// employeeService.deleteById(code);
		boolean deleted = employeeService.deleteById(code);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/employees-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<EmployeeListItem> listItems() {
		logger.info("listItems()...");
		List<EmployeeRecord> list = employeeService.findAll();
		List<EmployeeListItem> items = new LinkedList<EmployeeListItem>();
		for ( EmployeeRecord employee : list ) {
			items.add(new EmployeeListItem( employee ) );
		}
		return items;
	}

}
