/*
 * Created on 2017-11-03 ( Time 15:03:35 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.ShopRecord;
import org.demo.data.record.listitem.ShopListItem;


//--- Services 
import org.demo.persistence.ShopPersistence;
// import org.demo.business.service.impl.ShopServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'Shop' management.
 */
@Path("/shop")
public class ShopResource extends AbstractResourceController {

	private ShopPersistence shopService = PersistenceServiceProvider.getService(ShopPersistence.class);

	/**
	 * Constructor
	 */
	public ShopResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all shop entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<ShopRecord> findAll() {
		logger.info("findAll()...");
		return shopService.findAll();
	}

	/**
	 * Retrieves a shop using the given id.
	 * @param code code
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{code}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("code") String code) {
		logger.info("findById("+code+")...");
		ShopRecord record = shopService.findById(code);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new shop.
	 * @param shop shop
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(ShopRecord shop) {
		logger.info("create()...");
		if ( shopService.exists(shop) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			ShopRecord record = shopService.create(shop);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the shop identified by the given id
	 * @param shop shop entity
	 * @param code code 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{code}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public ShopRecord update(ShopRecord shop, @PathParam("code") String code) {
	public Response update(ShopRecord shop, @PathParam("code") String code) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		shop.setCode( code );
		boolean updated = shopService.update(shop);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given shop.
	 * @param shop shop entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(ShopRecord shop) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! shopService.exists(shop) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		ShopRecord record = shopService.save(shop);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a shop.
	 * @param code code
	 */
	@DELETE
	@Path("{code}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("code") String code) {
	public Response delete(@PathParam("code") String code) {
		logger.info("delete("+code+")...");
		// shopService.deleteById(code);
		boolean deleted = shopService.deleteById(code);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/shops-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<ShopListItem> listItems() {
		logger.info("listItems()...");
		List<ShopRecord> list = shopService.findAll();
		List<ShopListItem> items = new LinkedList<ShopListItem>();
		for ( ShopRecord shop : list ) {
			items.add(new ShopListItem( shop ) );
		}
		return items;
	}

}
