/*
 * Created on 2017-11-03 ( Time 15:03:35 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.SynopsisRecord;
import org.demo.data.record.listitem.SynopsisListItem;


//--- Services 
import org.demo.persistence.SynopsisPersistence;
// import org.demo.business.service.impl.SynopsisServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'Synopsis' management.
 */
@Path("/synopsis")
public class SynopsisResource extends AbstractResourceController {

	private SynopsisPersistence synopsisService = PersistenceServiceProvider.getService(SynopsisPersistence.class);

	/**
	 * Constructor
	 */
	public SynopsisResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all synopsis entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<SynopsisRecord> findAll() {
		logger.info("findAll()...");
		return synopsisService.findAll();
	}

	/**
	 * Retrieves a synopsis using the given id.
	 * @param bookId bookId
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{bookId}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("bookId") Integer bookId) {
		logger.info("findById("+bookId+")...");
		SynopsisRecord record = synopsisService.findById(bookId);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new synopsis.
	 * @param synopsis synopsis
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(SynopsisRecord synopsis) {
		logger.info("create()...");
		if ( synopsisService.exists(synopsis) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			SynopsisRecord record = synopsisService.create(synopsis);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the synopsis identified by the given id
	 * @param synopsis synopsis entity
	 * @param bookId bookId 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{bookId}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public SynopsisRecord update(SynopsisRecord synopsis, @PathParam("bookId") Integer bookId) {
	public Response update(SynopsisRecord synopsis, @PathParam("bookId") Integer bookId) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		synopsis.setBookId( bookId );
		boolean updated = synopsisService.update(synopsis);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given synopsis.
	 * @param synopsis synopsis entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(SynopsisRecord synopsis) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! synopsisService.exists(synopsis) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		SynopsisRecord record = synopsisService.save(synopsis);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a synopsis.
	 * @param bookId bookId
	 */
	@DELETE
	@Path("{bookId}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("bookId") Integer bookId) {
	public Response delete(@PathParam("bookId") Integer bookId) {
		logger.info("delete("+bookId+")...");
		// synopsisService.deleteById(bookId);
		boolean deleted = synopsisService.deleteById(bookId);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/synopsiss-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<SynopsisListItem> listItems() {
		logger.info("listItems()...");
		List<SynopsisRecord> list = synopsisService.findAll();
		List<SynopsisListItem> items = new LinkedList<SynopsisListItem>();
		for ( SynopsisRecord synopsis : list ) {
			items.add(new SynopsisListItem( synopsis ) );
		}
		return items;
	}

}
