/*
 * Created on 2017-11-03 ( Time 15:03:35 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.WorkgroupRecord;
import org.demo.data.record.listitem.WorkgroupListItem;


//--- Services 
import org.demo.persistence.WorkgroupPersistence;
// import org.demo.business.service.impl.WorkgroupServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'Workgroup' management.
 */
@Path("/workgroup")
public class WorkgroupResource extends AbstractResourceController {

	private WorkgroupPersistence workgroupService = PersistenceServiceProvider.getService(WorkgroupPersistence.class);

	/**
	 * Constructor
	 */
	public WorkgroupResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all workgroup entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<WorkgroupRecord> findAll() {
		logger.info("findAll()...");
		return workgroupService.findAll();
	}

	/**
	 * Retrieves a workgroup using the given id.
	 * @param id id
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{id}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("id") Short id) {
		logger.info("findById("+id+")...");
		WorkgroupRecord record = workgroupService.findById(id);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new workgroup.
	 * @param workgroup workgroup
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(WorkgroupRecord workgroup) {
		logger.info("create()...");
		if ( workgroupService.exists(workgroup) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			WorkgroupRecord record = workgroupService.create(workgroup);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the workgroup identified by the given id
	 * @param workgroup workgroup entity
	 * @param id id 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{id}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public WorkgroupRecord update(WorkgroupRecord workgroup, @PathParam("id") Short id) {
	public Response update(WorkgroupRecord workgroup, @PathParam("id") Short id) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		workgroup.setId( id );
		boolean updated = workgroupService.update(workgroup);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given workgroup.
	 * @param workgroup workgroup entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(WorkgroupRecord workgroup) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! workgroupService.exists(workgroup) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		WorkgroupRecord record = workgroupService.save(workgroup);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a workgroup.
	 * @param id id
	 */
	@DELETE
	@Path("{id}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("id") Short id) {
	public Response delete(@PathParam("id") Short id) {
		logger.info("delete("+id+")...");
		// workgroupService.deleteById(id);
		boolean deleted = workgroupService.deleteById(id);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/workgroups-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<WorkgroupListItem> listItems() {
		logger.info("listItems()...");
		List<WorkgroupRecord> list = workgroupService.findAll();
		List<WorkgroupListItem> items = new LinkedList<WorkgroupListItem>();
		for ( WorkgroupRecord workgroup : list ) {
			items.add(new WorkgroupListItem( workgroup ) );
		}
		return items;
	}

}
