/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:03:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.BadgePersistence ;
import org.demo.persistence.BadgePersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Badge persistence service
 * 
 * @author Telosys Tools
 *
 */
public class BadgePersistenceJpaTest extends BadgePersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	BadgePersistence persistenceService = new BadgePersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
