/*
 * Created on 2017-11-09 ( Date ISO 2017-11-09 - Time 10:26:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.BookPersistence ;
import org.demo.persistence.BookPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Book persistence service
 * 
 * @author Telosys Tools
 *
 */
public class BookPersistenceJpaTest extends BookPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	BookPersistence persistenceService = new BookPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
