/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:03:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.CountryPersistence ;
import org.demo.persistence.CountryPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Country persistence service
 * 
 * @author Telosys Tools
 *
 */
public class CountryPersistenceJpaTest extends CountryPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	CountryPersistence persistenceService = new CountryPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
