/*
 * Created on 2017-11-09 ( Date ISO 2017-11-09 - Time 10:26:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.CustomerPersistence ;
import org.demo.persistence.CustomerPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Customer persistence service
 * 
 * @author Telosys Tools
 *
 */
public class CustomerPersistenceJpaTest extends CustomerPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	CustomerPersistence persistenceService = new CustomerPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
