/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:03:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.EmployeePersistence ;
import org.demo.persistence.EmployeePersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Employee persistence service
 * 
 * @author Telosys Tools
 *
 */
public class EmployeePersistenceJpaTest extends EmployeePersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	EmployeePersistence persistenceService = new EmployeePersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
