/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:03:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.PublisherPersistence ;
import org.demo.persistence.PublisherPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Publisher persistence service
 * 
 * @author Telosys Tools
 *
 */
public class PublisherPersistenceJpaTest extends PublisherPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	PublisherPersistence persistenceService = new PublisherPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
