/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:03:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.ReviewPersistence ;
import org.demo.persistence.ReviewPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Review persistence service
 * 
 * @author Telosys Tools
 *
 */
public class ReviewPersistenceJpaTest extends ReviewPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	ReviewPersistence persistenceService = new ReviewPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
