/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:03:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.ShopPersistence ;
import org.demo.persistence.ShopPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Shop persistence service
 * 
 * @author Telosys Tools
 *
 */
public class ShopPersistenceJpaTest extends ShopPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	ShopPersistence persistenceService = new ShopPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
