/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:03:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.SynopsisPersistence ;
import org.demo.persistence.SynopsisPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Synopsis persistence service
 * 
 * @author Telosys Tools
 *
 */
public class SynopsisPersistenceJpaTest extends SynopsisPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	SynopsisPersistence persistenceService = new SynopsisPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
