/*
 * Created on 2017-11-03 ( Date ISO 2017-11-03 - Time 15:03:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.commons;

/**
 * The pattern defined here is used by the Persistence Service Provider <br>
 * to build the service implementation class name <br>
 * 
 * @author Telosys
 *
 */
public class PersistenceJpaServicePattern {

	public final static String  PATTERN = "%s.impl.jpa.%sJpa" ;
	
}
